# Generated by Django 4.0.2 on 2022-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
