# Generated by Django 4.0.2 on 2022-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_word', '0002_alter_word_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='published_at',
            field=models.DateField(null=True),
        ),
    ]
