# [START runtime]
# [START gaeflex_py_django_app_yaml]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT project.wsgi

beta_settings:
    cloud_sql_instances: preface-django-wordle:asia-east2:preface-django-wordle

runtime_config:
    python_version: 3
# [END gaeflex_py_django_app_yaml]
# [END runtime]
