# Generated by Django 4.0.2 on 2022-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attempts',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
