# Generated by Django 4.0.2 on 2022-02-06 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_app', '0002_alter_game_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_date',
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 10, 32, 17, 827826, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
